Project1/Controllers/EmployeeSalaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project1.Models;
using Project1.Controllers;

namespace Project1.Controllers
{
    public class EmployeeSalaryController : Controller
    {
        studentEntities1 db = new studentEntities1();
        // GET: EmployeeSalary
        public ActionResult Index1()
        {
            var employee_salary_details = db.employee_salary_details.ToList();
            return View(employee_salary_details);
        }
        public ActionResult Search(DateTime paid_date,DateTime paid_date2)
        {
            var employee_salary_details = db.employee_salary_details.Where(x=>x.paid_date>=paid_date && x.paid_date<=paid_date2).ToList();
            return View("Index1", employee_salary_details);
        }

        public ActionResult Create()
        {
            var employeeList = db.dbo_employee.ToList();
            ViewBag.employeeList = new SelectList(employeeList, "id", "FirstName");
            return View();
        }
        [HttpPost]
        public ActionResult Create(employee_salary_details employee_salary_details)
        {
            db.employee_salary_details.Add(employee_salary_details);
            db.SaveChanges();
            return RedirectToAction("Index1");
        }
        public ActionResult SaveData(employee_salary_details employee_salary_details)
        {
            db.employee_salary_details.Add(employee_salary_details);
            _ = db.SaveChanges();
            return RedirectToAction("Index1");
        }
        public ActionResult UpdateData(employee_salary_details employee_salary_details)
        {
            db.Entry(employee_salary_details).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index1");
        }

        public ActionResult Edit(int id)
        {
            employee_salary_details data = db.employee_salary_details.Find(id);
            return View(data);
        }
        public ActionResult Delete(int id)
        {
            employee_salary_details data = db.employee_salary_details.Find(id);   
            db.employee_salary_details.Remove(data);
            db.SaveChanges();
            return RedirectToAction("index1");
        }
    }
}

Project1/Views/EmployeeSalary/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<style>
    form {
        font-family: 'Open Sans';
        background-color: #FFFAF0;
    }
</style>

<form action="SaveData">
    <label>Employee Id</label>
    @Html.DropDownList("employeeList", null, "select", htmlAttributes: new { @Name= "employee_id",@class="form-control" });

    <label>Salary paid</label>
    <input type="text" name="salary_paid" class="form-control" />

    <label>Paid date</label>
    <input type="date" name="paid_date" class="form-control" />

    <br /><br />
    <input type="submit" name="submit" class="btn btn-success" value="Save" />
</form>

Project1/Views/EmployeeSalary/Edit.cshtml
@model Project1.Models.employee_salary_details
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<style>
    form {
        font-family: 'Open Sans';
        background-color: #FFFAF0;
    }
</style>
@using (Html.BeginForm("UpdateData", "EmployeeSalary"))
{

    <label>ID</label>
    <input type="text" name="id" value="@Model.id" class="form-control" />
    <label>Email</label>
    <input type="email" name="email" class="form-control" />
    <label>Number</label>
    <input type="number" name="number" class="form-control" />
    <br />
    <br />
    <input type="submit" name="submit" class="btn btn-success" value="Save" />

}

Project1/Views/EmployeeSalary/Index1.cshtml
@model IEnumerable<Project1.Models.employee_salary_details>
@{
    ViewBag.Title = "Index1";
}

<h2>Index1</h2>
@using (Html.BeginForm("Search", null))
{
    <label>search</label>
    <input type="date" name="paid_date" />
    <input type="date" name="paid_date2" />
    <input type="submit" value="Search" />
}
<p>
    @Html.ActionLink("create new", "Create")
</p>

<table class="table">
    <tr>
        <th>SN</th>
        <th>Employee id</th>
        <th>Salary Amount</th>
        <th>Paid Date</th>
        <th>Action</th>
    </tr>

    @{ int sn = 0;}
    @foreach (var item in Model)
    {
        <tr>
            <td>@(++sn))</td>
            <td>@item.dbo_employee.FirstName</td>
            <td>@item.salary_paid</td>
            <td>@item.paid_date</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id })|
                @Html.ActionLink("Details", "Details", new { id = item.id })|
                @Html.ActionLink("Delete", "Delete", new { id = item.id })|
            </td>
        </tr>
    }
    <tr>

        <td></td>
        <td>Total</td>
        <td colspan="2">@(Model.Sum(x=>x.salary_paid))</td>
    </tr>
</table>